# Generated by Django 5.2.5 on 2025-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='lead',
            name='message_ka',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='lead',
            name='message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='lead',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lead',
            name='name_ka',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lead',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
